---
- name: Play client
  hosts: client
  become: yes
  gather_facts: false
  tasks:

  - name: install epel-release
    yum:
      state: present
      name:
        - epel-release

  - name: Install packages for openvpn
    yum:
      name: 
        - tcpdump
        - policycoreutils-python
        - openvpn
        - iperf3
        - vim

  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled